server:
  port: 20020
  servlet:
    context-path: /T
    encoding:
      charset: UTF-8
      force-response: true
  error:
    whitelabel.enabled: false
    path: /common

spring:
  application:
    name: T
  #  profiles:
  #    active: @env@
  mvc:
    throw-exception-if-no-handler-found: true


fileupload:
  Repository: D:\upfiles

base:
  register:
    enum:
      url: http://127.0.0.1:20000/Base/code/putCode
      packages:
        - hyren.serv6.t.contants

hyren:
  fd:
    db:
      datasource:
        - name: default
          way: POOL
          disabled: false
          dbtype: POSTGRESQL
          driver: org.postgresql.Driver
          url: jdbc:postgresql://172.168.0.24:20090/hrsdxg_6_test
          username: hrsdxg
          password: hrsdxg
          minPoolSize: 10
          maxPoolSize: 20
          poolProperties:
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048

knife4j:
  enableAggregation: true
  cloud:
    enable: true
